### ISSUE TITLE
Incorrect function list used for auto-completion

### ISSUE THREAD

**Issue by christippett** [joshtemple/harlequin-bigquery#9]
The script used for populating BigQuery's built-in functions seems to be coming from a Snowflake resource ([fivetran/zetasql-snowflake](https://raw.githubusercontent.com/fivetran/zetasql-snowflake/master/zetasql/public/builtin_function.proto)). There's obviously a lot of overlap between Snowflake and BigQuery, but even then the majority of the list is made up of invalid/irrelevant function names (e.g. `ANON_SUM_UINT`). Legitimate functions unique to BigQuery such as [`DLP_DETERMINISTIC_ENCRYPT`](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#dlp_deterministic_encrypt), [`SAFE_CAST`](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#safe_casting), etc are missing entirely.

I also noticed in the sqlite adapter that the function list differentiates between aggregation queries (`type_label=agg`) and other functions (`type_label=fn`). See [here](https://github.com/tconbeer/harlequin/blob/0083dbf1be299355ca7f3b6973c77ae68fc563bb/src/harlequin_sqlite/completions.py#L220-L228). Potentially something to consider when reviewing the list for BigQuery?

**Comment by christippett** [comment]
[This page](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#function_list) might be a more appropriate resource for getting a list of BigQuery function names. Each section has a **Function list** sub-heading with a table outlining every function – there's an obvious pattern in the way the page is structured that would make it a potentially good (and reliable?) candidate for scraping.

**Comment by joshtemple** [comment]
Thanks @christippett for pointing this out. Not sure what I was doing with the previous list... but the function you referenced led me to [another repo](https://github.com/kiibo382/bigquery-functions) that seems to have a more complete list of functions, which saves me the time of having to scrape the docs myself.
